import Head from "next/head";
import withAuth from "../hoc/auth";

function Layout({ children }) {
    return (
        <>
            <Head>
                <title>NoteX</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>{children}</main>
        </>
    )
}

export default withAuth(Layout);